name: unfold_edu
description: Educational unfolding app
version: 1.0.0

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  cupertino_icons: ^1.0.2
  protobuf: ^6.0.0
  grpc: ^5.1.0
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  file_picker: ^10.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
